services:
  - type: web
    name: portfolio
    runtime: java
    buildCommand: mvn clean install -DskipTests
    startCommand: java -jar target/portfolio-0.0.1-SNAPSHOT.jar
    envVars:
      - key: PORT
        generateValue: true
    autoDeploy: true